name: .NET Publish

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          - { name: windows-latest, arch: win }
          - { name: ubuntu-latest, arch: linux }
        arch: [x64, x86]
        
    runs-on: ${{ matrix.os.name }}  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
                             
    env:
      Solution_Name: OsuPlayer.sln                         # Replace with your solution name, i.e. MyWpfApp.sln.

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: dotnet restore
      
    - name: Build
      run: |
        cd OsuPlayer
        dotnet build -c Release --no-restore
        dotnet publish -c Release -o ../releases/${{ matrix.os.arch }}-${{ matrix.arch }} -r ${{ matrix.os.arch }}-${{ matrix.arch }}
